import { gql } from '@apollo/client'

/**
 * GraphQL Queries for Rick and Morty API.
 * These queries are used by Apollo Client.
 * Types are generated by graphql-codegen from these definitions.
 * @see https://rickandmortyapi.com/documentation/#graphql
 */

/**
 * Fetches a paginated list of characters with optional filters.
 * @param page - Page number (1-indexed)
 * @param filter - Optional filter object with name, status, species, gender
 */
export const GET_CHARACTERS = gql`
    query GetCharacters($page: Int!, $filter: FilterCharacter) {
        characters(page: $page, filter: $filter) {
            info {
                count
                pages
                next
                prev
            }
            results {
                id
                name
                status
                species
                type
                gender
                origin {
                    name
                }
                location {
                    name
                }
                image
            }
        }
    }
`

/**
 * Fetches a single character by ID.
 * Includes episode information for detailed view.
 * @param id - Character ID
 */
export const GET_CHARACTER = gql`
    query GetCharacter($id: ID!) {
        character(id: $id) {
            id
            name
            status
            species
            type
            gender
            origin {
                name
            }
            location {
                name
            }
            image
            episode {
                id
                name
                episode
            }
            created
        }
    }
`
